name: Stock Bot

on:
  schedule:
    # 1. 아침 8시 (매일)
    - cron: '0 23 * * *'
    # 2. 오후 3시 10분 (1-5를 *로 변경하여 매일 실행)
    - cron: '10 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 yfinance pandas

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
